# Generated by Django 2.0.6 on 2019-06-22 12:57

from django.db import migrations, models
import django.utils.timezone
import imagekit.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImageSource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('avatar_thumbnail', imagekit.models.fields.ProcessedImageField(upload_to='image/image_source/%Y%m%d', verbose_name='图片')),
            ],
            options={
                'verbose_name_plural': '图库',
                'ordering': ('-created',),
            },
        ),
    ]
