# Generated by Django 2.0.6 on 2019-07-13 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topic', '0002_auto_20190704_2326'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='body',
            field=models.TextField(default=1, verbose_name='正文'),
            preserve_default=False,
        ),
    ]
