# Generated by Django 2.0.6 on 2019-06-29 07:54

import apps.userinfo.models
from django.db import migrations, models
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('userinfo', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserInfo',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='blood',
            field=models.SmallIntegerField(choices=[(0, ''), (1, 'A'), (2, 'B'), (3, 'AB'), (4, 'O')], default=0, verbose_name='血型'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='link',
            field=models.URLField(blank=True, help_text='提示：网址必须填写以http开头的完整形式', verbose_name='个人网址'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='startWorkout',
            field=models.DateField(blank=True, null=True, verbose_name='开始健身日'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to=apps.userinfo.models.user_directory_path, verbose_name='头像'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='gender',
            field=models.SmallIntegerField(choices=[(0, ''), (1, '男♂'), (2, '女♀'), (3, '⚧')], default=0, verbose_name='性别'),
        ),
    ]
