# Generated by Django 2.0.6 on 2019-07-04 14:26

from django.db import migrations, models
import django.db.models.deletion
import imagekit.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='删除标记')),
                ('title', models.CharField(max_length=200, verbose_name='标题')),
                ('is_finished', models.BooleanField(default=False, verbose_name='已完结')),
                ('avatar_thumbnail', imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to='image/comic/%Y%m%d', verbose_name='缩略图')),
                ('url', models.URLField(blank=True)),
            ],
            options={
                'verbose_name_plural': '漫画',
                'ordering': ('create_time',),
            },
        ),
        migrations.CreateModel(
            name='GithubRepo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='删除标记')),
                ('user', models.CharField(default='stacklens', max_length=100, verbose_name='拥有者')),
                ('repo', models.CharField(max_length=500, verbose_name='仓库名')),
                ('description', models.CharField(max_length=500, verbose_name='简介')),
            ],
            options={
                'verbose_name_plural': 'Github仓库',
            },
        ),
        migrations.AddField(
            model_name='comic',
            name='github_repo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='comic.GithubRepo'),
        ),
    ]
