# Generated by Django 2.0.6 on 2019-06-22 12:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vlog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='标题')),
                ('body', models.TextField(blank=True, verbose_name='正文')),
                ('avatar_url', models.URLField(verbose_name='标题图链接')),
                ('video_url', models.URLField(blank=True, null=True, verbose_name='视频链接')),
                ('iframe', models.CharField(blank=True, max_length=400, null=True, verbose_name='嵌入代码')),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('total_views', models.PositiveIntegerField(default=0, verbose_name='浏览量')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vlog', to=settings.AUTH_USER_MODEL, verbose_name='作者')),
            ],
            options={
                'verbose_name_plural': '视频',
                'ordering': ('-created',),
            },
        ),
    ]
